config/routes.rb
Rails.application.routes.draw do
  resources :events
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'pages#home'

  resources :events do
    post 'rsvps', to: 'rsvps#create', on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new 
    if user.admin?
      can :manage, :all
      can :access, :rails_admin
      can :access, :dashboard 
      can :manage, Event
    end
    if user.creator?
      can :read, :all
      can :manage, Event, :user_id => user.id
      can :create, Event
      can :edit, Event


    else
      can :read,  :all
      can :create, Event

    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    geocoded_by :address
    after_validation :geocode, :if => :address_changed?
  belongs_to :user
  has_many :rsvps
  has_many :users, through: :rsvps
  validates :title, presence: true, length: { minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 600}
  validates :address, presence: true, length: { minimum: 6, maximum: 100}
end

app/models/rsvp.rb
class Rsvp < ApplicationRecord
    belongs_to :user
    belongs_to :event
    validates :user_id, uniqueness: { scope: :event_id }
  
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events
  has_many :rsvps
  has_many :events, through: :rsvps

  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception

     before_action :configure_permitted_parameters, if: :devise_controller?

     protected

          def configure_permitted_parameters
               devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}

               devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
          end
    
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.paginate(page: params[:page], per_page: 5)
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.user = current_user
    

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :description, :start, :end, :user_id, :address, :latitude, :longitude)
    end

    # add user level
    def require_same_user
      if current_user != @event.user and !current_user.admin?
          flash[:notice] = "You can only edit or delete your own articles"
          redirect_to root_path
      end
   end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
      redirect_to events_path if user_signed_in?
    end
  
    
  end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
    def create
      @rsvps = current_user.rsvps.build({event_id: params[:id]})
      
      
      if @rsvps.save
        EventMailer.with(rsvp: @rsvps).send_reminder_mail.deliver_now
        time_now = DateTime.now
        time_of_event = @rsvps.event.start
        hours_between = TimeDifference.between(time_now, time_of_event).in_hours
        time_to_notify = hours_between-24
        RemindMailer.with(rsvp: @rsvps).send_tomorrow_mail.deliver_later!(wait: time_to_notify.hours)
        flash[:notice] = "You have RSVP'd"
        redirect_to event_path
      end
    end

    def rsvps
      @rsvps=rsvps.new
    end
    
    
end

 



  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="container">
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :title, class: "col-2 col-form-label text-info" %>
    <div class="col-10">
      <%= form.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :description, class: "col-2 col-form-label text-info" %>
    <div class="col-10">
      <%= form.text_area :description, rows:10, class: "form-control shadow rounded", placeholder: "Description of article" %>
    </div>
  </div> 

  <div class="form-group row justify-content-center">
    <%= form.label :start, class: "col-2 col-form-label text-info" %>
    <div class="col-10">
    <%= form.datetime_select :start %>
    </div>
  </div>
      
  <div class="form-group row justify-content-center">
    <%= form.label :end, class: "col-2 col-form-label text-info" %>
    <div class="col-10">
    <%= form.datetime_select :end %>
    </div>
  </div>

  <div class="form-group row">
  <%= form.label :address, class: "col-2 col-form-label text-info" %>
  <div class="col-10">
    <%= form.text_area :address, rows:3, class: "form-control shadow rounded", placeholder: "Address" %>
  </div>
  </div> 

  <div class="form-group row justify-content-center">
    <%= form.submit class: "btn btn-outline-info btn-lg" %>
  </div>


<% end %>

</div>

app/views/events/edit.html.erb
<h2 class= "text-center mt-4 font-weight-bold">Editing Event</h2>

<%= render 'form', event: @event %>

<%=link_to "Show", @event, class: "btn btn-outline-success mb-4" %>
<%=link_to "Back", events_path(@events), class: "btn btn-outline-success mb-4" %>

app/views/events/index.html.erb
<h2 class= "text-center mt-4 font-weight-bold">ALL EVENTS</h2>

<div class="flickr_pagination">
  <%= will_paginate @events, :container => false %>
</div>

<div class="container">
<% @events.each do |event| %>
<div class="row justify-content-md-center">
    <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%= link_to event.title, event_path(event), class: "text-success" %></h5>
            <p class="card-text"> <strong>Details:</strong> <%= truncate(event.description, length: 100) %></p>
            <p class="card-text"><strong>Address:</strong><%= truncate(event.address, length: 100) %></p>
            <p class="card-text"><strong>Start:</strong><%= event.start.strftime('%m/%d/%y %I:%M %p')%></p>
            <p class="card-text"><strong>End:</strong><%= event.end.strftime('%m/%d/%y %I:%M %p') %></p>

            

            <%=link_to "View", event_path(event), class: "btn btn-outline-success" %>
            <% if user_signed_in? && (event.user == current_user || current_user.admin?) %>
            <%=link_to "Edit", edit_event_path(event), class: "btn btn-outline-info" %>
            <%=link_to "Delete", event_path(event), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
            
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(event.created_at) %>ago,
            edited <%= time_ago_in_words(event.updated_at) %> ago</small>
          </div>
        </div>
    </div>
    </div>
<% end %>
</div>



<div class="flickr_pagination mb-4">
  <%= will_paginate @events, :container => false %>
</div>


 

app/views/events/new.html.erb
<h2 class= "text-center mt-4 font-weight-bold">New Event</h2>

<%= render 'form', event: @event %>


<%=link_to "Back", events_path(@events), class: "btn btn-outline-success mb-4" %>

app/views/events/show.html.erb
<h2 class= "text-center mt-4"><%= @event.title %></h2>
<div class="container">
<div class="row justify-content-md-center">
    <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
         
          <div class="card-body">
            <div class="card-text text-center"><%= simple_format(@event.description) %></div>
            <p class="card-text"><strong>Start: </strong><%= @event.start.strftime('%m/%d/%y %I:%M %p')%></p>
            <p class="card-text"><strong>End: </strong><%= @event.end.strftime('%m/%d/%y %I:%M %p')%></p>
            <p class="card-text"><strong>Address: </strong><%= truncate(@event.address, length: 100) %></p>
            <p class="card-text"><strong>How many people will attend this coming event? : </strong><%= pluralize(@event.users.count, "attendee") %></p>
            
            <% if user_signed_in? && (@event.user_id == current_user.id) %>
              <%= link_to "You're the organizer of this event", event_path, :class => 'btn btn-outline-success'  %>
            <% end %>
           
            <% if user_signed_in? && (@event.user_id != current_user.id) %>
            <% unless Rsvp.exists?(event: @event.id, user: @event.user.id = current_user.id) %>
              <div class="rsvp mt-2"><%= button_to "Attend", rsvps_event_path(@event), class: "btn btn-outline-success" %></div>
              <% else %>
              <%= link_to "You're going!", event_path, :class => 'btn btn-outline-success'  %>
            <% end %>
            <% end %>

            <% if user_signed_in? %>
            <% link_to " ", event_path, :class => 'btn btn-outline-success'  %>
            <% else %>
            <%= link_to "Join Events!", new_user_registration_path, :class => 'btn btn-outline-success'  %>
            <% end %>


            
            <div class="map mt-4 mb-4"><%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@event.latitude},#{@event.longitude}&markers=#{@event.latitude},#{@event.longitude}&zoom=12&size=450x400&sensor=false&key=AIzaSyD-rwNYF7BhFWgCNCmuZHEn1JEqkjlcfMY",
              class: 'img-fluid img-rounded', alt: "#{@event} on the map"%>
            </div>

            <div class="row justify-content-md-center">
            <ol>
            <p><strong>This event is organized by: </strong><%= truncate(@event.user.name, length: 100) %></p>
            <p><strong>Name list of attendee</strong></p>
            <% @event.users.sort.each do |user| %>
             <li> <%= user.name %> </li>
            <% end %>
            </ol>
            </div>

            <% if user_signed_in? && (@event.user == current_user || current_user.admin?) %>
            <%=link_to "Edit", edit_event_path(@event), class: "btn btn-outline-info" %>
            <%=link_to "Delete", event_path(@event), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
            <%=link_to "Back", events_path(@events), class: "btn btn-outline-secondary" %>
        
          </div>
        </div>
    </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
<div class="container text-center">
  <small>Copyright &copy; 2020 Events!</small>
</div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<%= link_to "EVENTS!", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      <%= link_to "Explore", events_path, :class => 'nav-link'  %>
      </li>
      <li class="nav-item active">
          <% if user_signed_in? %>
            <%=link_to "Create a new event", new_event_path, class: "nav-link" %>
          <% end %>
      </li>
    </ul>
    <p class="navbar-text-white float-right">
        <% if user_signed_in? %>
        Logged in as <strong><%= current_user.name %></strong>
            <%= link_to "Admin", rails_admin_path, class: "navbar-link" if current_user.admin? %> |
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
    </p>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>We are what we do | Events!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
    </div>
    

    <%= render 'layouts/navigation' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  
  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron jumbotron-fluid text-center text-white" id="home-jumbotron">
  <div class="container">
    <h1 class="display-4">The real world is calling</h1>
    <p class="lead">Join our events to meet people, try somthing new, or do more of what you love.</p>
        <%= link_to "Join Events!", new_user_registration_path, class: "btn btn-success btn-lg" %>
  </div>
</div>